<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Task;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{

    public function getListTasks()
    {
        return $this->createQueryBuilder('t')
            ->select('t')
            ->andWhere('t.status = :status' )
            ->setParameter(':status', Task::STATUS_OPENED)
            ->getQuery()
            ->getResult();
    }
}
