# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
  app.task.manager:
      class: AppBundle\Manager\TaskManager
      arguments:
        - "@=service('doctrine').getManager()"

  app.category.manager:
      class: AppBundle\Manager\CategoryManager
      arguments:
        - "@=service('doctrine').getManager()"

  app.normalizer.user:
      class: AppBundle\Serializer\Normalizer\CategoryNormalizer
      tags:
        - { name: serializer.normalizer}